#!/usr/bin/env bash

set -e


function git_branch_name() {
    git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/\1/'
}

function e() {
    echo "################ $@ ################"
    $@
}


CURRENT_BRANCH=$(git_branch_name)
TARGET_BRANCH=$1


if [[ -z $TARGET_BRANCH ]]; then
  TARGET_BRANCH=$CURRENT_BRANCH
fi


if [[ $CURRENT_BRANCH = feature/* ]]; then
  e git stash
  e git checkout master
  e git pull
  e git merge "$CURRENT_BRANCH"
  e git push
  e npm publish
  if [[ ${TARGET_BRANCH} != master ]]; then
    e git checkout "$TARGET_BRANCH"
    e git merge master
    e git push
    e git stash pop
  fi
elif [[ $CURRENT_BRANCH = master ]]; then
  e git push
  e npm publish
  if [[ $TARGET_BRANCH = feature/* ]]; then
    e git checkout "$TARGET_BRANCH"
    e git merge master
    e git push
    e git stash pop
  fi
fi
